name: Build and Publish Image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types: ["published"]

jobs:
  build-and-publish:
    name: Build and Publish
    uses: cmu-sei/Crucible-Github-Actions/.github/workflows/docker-build.yaml@docker-v1.1.2
    with:
      imageName: cmusei/cite-ui
      versionMode: npm
      versionFiles: package.json
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
